export const pun = {
  "items": [
    `A polar bear walks into a bar and says to the bartender “I’ll have a rum …………………. and coke.” The bartender asks, “What’s with the big pause?”The bear shrugs. “I was born with them.”`,
    `What do you call an alligator in a vest? An investigator.`,
    `What did one eye say to the other? Just between you and me, something smells.`,
    `How does Moses make coffee? Hebrews it.`,
    `A photon checks into a hotel. The front desk asks if it has any luggage. It replies “no, I’m traveling light”`,
    `I can’t stand Russian dolls. They’re so full of themselves.`,
    `If you see an Apple Store get robbed, does that make you an iWitness?`,
    `The past, the present and the future all walk into a bar. It was tense.`,
    `Don’t ever believe an atom, they make up everything.`,
    `I’m glad I know sign language, it’s pretty handy.`,
    `Why did the scarecrow get an award? He was outstanding in his field.`,
    `Why did the can crusher quit her job? It was soda-pressing.`,
    `What do you call a broken can opener? A can’t opener.`,
    `Why do people love switzerland? Well, the flag is a big plus. Unlike Canada’s, which I could take or leaf.`,
    `Did you hear about the sale on paddles? It was quite the oar-deal.`,
    `What do you call a lawyer who can cook? A sue chef`,
    `I’m reading a book about anti-gravity. I just can’t put it down.`,
    `I stayed up all night to see where the sun went. Then it dawned on me.`,
    `Broken pencils are pointless.`,
    `I don’t enjoy computer jokes. Not one bit.`,
    `I changed my phone’s name to Titanic. It’s syncing now.`,
    `Jokes about german sausage are the wurst.`,
    `I refuse to work with compost, it’s degrading.`,
    `Did you hear about the banker who left her job? She just lost interest.`,
    `How do you measure the quality of my puns? A sighsmograph!`,
    `A Steak Pun is a Rare Medium Well Done`
  ]
}
